// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRuYWm7SE4D3eqx3cN0lStPrxAyuB-Lt4',
    appId: '1:512763439180:web:b99ab774968fe1c7782ce9',
    messagingSenderId: '512763439180',
    projectId: 'aharexpress',
    authDomain: 'aharexpress.firebaseapp.com',
    storageBucket: 'aharexpress.firebasestorage.app',
    measurementId: 'G-JLJ4HC6KJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrSnrtssEgj8OwSTUlAn81CWSr-51imw',
    appId: '1:512763439180:android:5e57753d009e5fc4782ce9',
    messagingSenderId: '512763439180',
    projectId: 'aharexpress',
    storageBucket: 'aharexpress.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJzTNXyIDfzw1-5dxxC78N2VBYZed0wOY',
    appId: '1:512763439180:ios:e8b9a2868ecadb82782ce9',
    messagingSenderId: '512763439180',
    projectId: 'aharexpress',
    storageBucket: 'aharexpress.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJzTNXyIDfzw1-5dxxC78N2VBYZed0wOY',
    appId: '1:512763439180:ios:e8b9a2868ecadb82782ce9',
    messagingSenderId: '512763439180',
    projectId: 'aharexpress',
    storageBucket: 'aharexpress.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRuYWm7SE4D3eqx3cN0lStPrxAyuB-Lt4',
    appId: '1:512763439180:web:0febfd8c499c4237782ce9',
    messagingSenderId: '512763439180',
    projectId: 'aharexpress',
    authDomain: 'aharexpress.firebaseapp.com',
    storageBucket: 'aharexpress.firebasestorage.app',
    measurementId: 'G-KCQP0E0QCY',
  );
}
